// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design implementation internals
// See Vtop.h for the primary calling header

#include "Vtop___024root.h"
#include "Vtop__Syms.h"

#include "verilated_dpi.h"

void Vtop___024root___initial__TOP__1(Vtop___024root* vlSelf) VL_ATTR_COLD;

void Vtop___024root___eval_initial(Vtop___024root* vlSelf) {
    if (false && vlSelf) {}  // Prevent unused
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root___eval_initial\n"); );
    // Body
    Vtop___024root___initial__TOP__1(vlSelf);
    vlSelf->__Vclklast__TOP__clock = vlSelf->clock;
}

void Vtop___024root___settle__TOP__2(Vtop___024root* vlSelf) VL_ATTR_COLD;

void Vtop___024root___eval_settle(Vtop___024root* vlSelf) {
    if (false && vlSelf) {}  // Prevent unused
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root___eval_settle\n"); );
    // Body
    Vtop___024root___settle__TOP__2(vlSelf);
    vlSelf->__Vm_traceActivity[1U] = 1U;
    vlSelf->__Vm_traceActivity[0U] = 1U;
}

void Vtop___024root___final(Vtop___024root* vlSelf) {
    if (false && vlSelf) {}  // Prevent unused
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root___final\n"); );
}

void Vtop___024root___ctor_var_reset(Vtop___024root* vlSelf) {
    if (false && vlSelf) {}  // Prevent unused
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root___ctor_var_reset\n"); );
    // Body
    vlSelf->clock = VL_RAND_RESET_I(1);
    vlSelf->reset = VL_RAND_RESET_I(1);
    vlSelf->io_inst = VL_RAND_RESET_I(32);
    vlSelf->io_pc = VL_RAND_RESET_Q(64);
    vlSelf->io_step = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__arbiter_io_ifu_axi_out_rdata = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__arbiter_io_ifu_axi_out_rlast = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__arbiter_io_ifu_axi_out_rvalid = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__arbiter_io_lsu_axi_out_rdata = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__arbiter_io_lsu_axi_out_rlast = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__arbiter_io_lsu_axi_out_rvalid = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__arbiter_io_lsu_axi_out_bvalid = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__arbiter_io_axi_out_arvalid = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__arbiter_io_axi_out_rready = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__arbiter_io_axi_out_awvalid = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__arbiter_io_axi_out_wvalid = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__arbiter_io_axi_out_bready = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache_io_to_ifu_rvalid = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache_io_to_axi_arvalid = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache_io_to_axi_rready = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache_io_to_axi_arvalid = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache_io_to_axi_rready = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache_io_to_axi_awaddr = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__d_cache_io_to_axi_awlen = VL_RAND_RESET_I(8);
    vlSelf->top__DOT__d_cache_io_to_axi_awvalid = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache_io_to_axi_wdata = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__d_cache_io_to_axi_wstrb = VL_RAND_RESET_I(8);
    vlSelf->top__DOT__d_cache_io_to_axi_wvalid = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache_io_to_axi_bready = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__axi_io_axi_out_rlast = VL_RAND_RESET_I(1);
    for (int __Vi0=0; __Vi0<32; ++__Vi0) {
        vlSelf->top__DOT__Register__DOT__Reg[__Vi0] = VL_RAND_RESET_Q(64);
    }
    for (int __Vi0=0; __Vi0<32; ++__Vi0) {
        vlSelf->top__DOT__Register__DOT__reg_trace__DOT__traceregs[__Vi0] = VL_RAND_RESET_Q(64);
    }
    vlSelf->top__DOT__IFU__DOT__fs_valid = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__IFU__DOT__fs_pc = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__IFU__DOT__fs_inst = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__IFU__DOT__seq_pc = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__IFU__DOT___GEN_3 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__IFU__DOT__inst_ready = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__IFU__DOT___GEN_5 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__arbiter__DOT__state = VL_RAND_RESET_I(2);
    vlSelf->top__DOT__arbiter__DOT___GEN_0 = VL_RAND_RESET_I(2);
    vlSelf->top__DOT__arbiter__DOT___GEN_94 = VL_RAND_RESET_I(2);
    vlSelf->top__DOT__arbiter__DOT___GEN_126 = VL_RAND_RESET_I(2);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT__ram_0_0);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT__ram_0_1);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT__ram_0_2);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT__ram_0_3);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT__ram_0_4);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT__ram_0_5);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT__ram_0_6);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT__ram_0_7);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT__ram_0_8);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT__ram_0_9);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT__ram_0_10);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT__ram_0_11);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT__ram_0_12);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT__ram_0_13);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT__ram_0_14);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT__ram_0_15);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT__ram_1_0);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT__ram_1_1);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT__ram_1_2);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT__ram_1_3);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT__ram_1_4);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT__ram_1_5);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT__ram_1_6);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT__ram_1_7);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT__ram_1_8);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT__ram_1_9);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT__ram_1_10);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT__ram_1_11);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT__ram_1_12);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT__ram_1_13);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT__ram_1_14);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT__ram_1_15);
    vlSelf->top__DOT__i_cache__DOT__tag_0_0 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT__tag_0_1 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT__tag_0_2 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT__tag_0_3 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT__tag_0_4 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT__tag_0_5 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT__tag_0_6 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT__tag_0_7 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT__tag_0_8 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT__tag_0_9 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT__tag_0_10 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT__tag_0_11 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT__tag_0_12 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT__tag_0_13 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT__tag_0_14 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT__tag_0_15 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT__tag_1_0 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT__tag_1_1 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT__tag_1_2 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT__tag_1_3 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT__tag_1_4 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT__tag_1_5 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT__tag_1_6 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT__tag_1_7 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT__tag_1_8 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT__tag_1_9 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT__tag_1_10 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT__tag_1_11 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT__tag_1_12 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT__tag_1_13 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT__tag_1_14 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT__tag_1_15 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT__valid_0_0 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT__valid_0_1 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT__valid_0_2 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT__valid_0_3 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT__valid_0_4 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT__valid_0_5 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT__valid_0_6 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT__valid_0_7 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT__valid_0_8 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT__valid_0_9 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT__valid_0_10 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT__valid_0_11 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT__valid_0_12 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT__valid_0_13 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT__valid_0_14 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT__valid_0_15 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT__valid_1_0 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT__valid_1_1 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT__valid_1_2 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT__valid_1_3 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT__valid_1_4 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT__valid_1_5 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT__valid_1_6 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT__valid_1_7 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT__valid_1_8 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT__valid_1_9 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT__valid_1_10 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT__valid_1_11 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT__valid_1_12 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT__valid_1_13 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT__valid_1_14 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT__valid_1_15 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT__way0_hit = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT__way1_hit = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT__unuse_way = VL_RAND_RESET_I(2);
    vlSelf->top__DOT__i_cache__DOT__receive_data_0 = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__i_cache__DOT__receive_data_1 = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__i_cache__DOT__receive_data_2 = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__i_cache__DOT__receive_data_3 = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__i_cache__DOT__receive_data_4 = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__i_cache__DOT__receive_data_5 = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__i_cache__DOT__receive_data_6 = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__i_cache__DOT__receive_data_7 = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__i_cache__DOT__receive_num = VL_RAND_RESET_I(3);
    vlSelf->top__DOT__i_cache__DOT__quene = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_13 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_31 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_46 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_64 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT__state = VL_RAND_RESET_I(3);
    vlSelf->top__DOT__i_cache__DOT___GEN_69 = VL_RAND_RESET_I(3);
    vlSelf->top__DOT__i_cache__DOT___GEN_71 = VL_RAND_RESET_I(3);
    vlSelf->top__DOT__i_cache__DOT___GEN_83 = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__i_cache__DOT___GEN_84 = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__i_cache__DOT___GEN_85 = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__i_cache__DOT___GEN_86 = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__i_cache__DOT___GEN_87 = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__i_cache__DOT___GEN_88 = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__i_cache__DOT___GEN_89 = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__i_cache__DOT___GEN_90 = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__i_cache__DOT___GEN_91 = VL_RAND_RESET_I(3);
    vlSelf->top__DOT__i_cache__DOT___GEN_92 = VL_RAND_RESET_I(3);
    vlSelf->top__DOT__i_cache__DOT___GEN_577 = VL_RAND_RESET_I(3);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_578);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_579);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_580);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_581);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_582);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_583);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_584);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_585);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_586);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_587);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_588);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_589);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_590);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_591);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_592);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_593);
    vlSelf->top__DOT__i_cache__DOT___GEN_594 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_595 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_596 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_597 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_598 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_599 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_600 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_601 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_602 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_603 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_604 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_605 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_606 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_607 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_608 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_609 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_610 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_611 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_612 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_613 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_614 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_615 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_616 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_617 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_618 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_619 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_620 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_621 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_622 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_623 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_624 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_625 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_626 = VL_RAND_RESET_I(1);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_627);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_628);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_629);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_630);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_631);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_632);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_633);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_634);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_635);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_636);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_637);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_638);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_639);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_640);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_641);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_642);
    vlSelf->top__DOT__i_cache__DOT___GEN_643 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_644 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_645 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_646 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_647 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_648 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_649 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_650 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_651 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_652 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_653 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_654 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_655 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_656 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_657 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_658 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_659 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_660 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_661 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_662 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_663 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_664 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_665 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_666 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_667 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_668 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_669 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_670 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_671 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_672 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_673 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_674 = VL_RAND_RESET_I(1);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_1009);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_1025);
    vlSelf->top__DOT__i_cache__DOT___GEN_1034 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_1043 = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__i_cache__DOT___GEN_1044 = VL_RAND_RESET_I(3);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT__ram_0_0);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT__ram_1_0);
    vlSelf->top__DOT__d_cache__DOT__valid_0_0 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT__valid_1_0 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT__dirty_0_0 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT__dirty_1_0 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT__way0_hit = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT__way1_hit = VL_RAND_RESET_I(1);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT__write_back_data);
    vlSelf->top__DOT__d_cache__DOT__write_back_addr = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__d_cache__DOT__unuse_way = VL_RAND_RESET_I(2);
    vlSelf->top__DOT__d_cache__DOT__receive_data_0 = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__d_cache__DOT__receive_data_1 = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__d_cache__DOT__receive_data_2 = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__d_cache__DOT__receive_data_3 = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__d_cache__DOT__receive_data_4 = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__d_cache__DOT__receive_data_5 = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__d_cache__DOT__receive_data_6 = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__d_cache__DOT__receive_data_7 = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__d_cache__DOT__receive_num = VL_RAND_RESET_I(3);
    vlSelf->top__DOT__d_cache__DOT__quene = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT__state = VL_RAND_RESET_I(3);
    vlSelf->top__DOT__d_cache__DOT___GEN_72 = VL_RAND_RESET_I(3);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___GEN_205);
    vlSelf->top__DOT__d_cache__DOT___GEN_221 = VL_RAND_RESET_I(1);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___GEN_237);
    vlSelf->top__DOT__d_cache__DOT___GEN_253 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_1442 = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__d_cache__DOT___GEN_1443 = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__d_cache__DOT___GEN_1444 = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__d_cache__DOT___GEN_1445 = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__d_cache__DOT___GEN_1446 = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__d_cache__DOT___GEN_1447 = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__d_cache__DOT___GEN_1448 = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__d_cache__DOT___GEN_1449 = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__d_cache__DOT___GEN_1450 = VL_RAND_RESET_I(3);
    vlSelf->top__DOT__d_cache__DOT___GEN_1451 = VL_RAND_RESET_I(3);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___GEN_1452);
    vlSelf->top__DOT__d_cache__DOT___GEN_1484 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_1500 = VL_RAND_RESET_I(1);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___GEN_1501);
    vlSelf->top__DOT__d_cache__DOT___GEN_1533 = VL_RAND_RESET_I(1);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___GEN_1549);
    vlSelf->top__DOT__d_cache__DOT___GEN_1551 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_1567 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_2087 = VL_RAND_RESET_I(3);
    vlSelf->top__DOT__d_cache__DOT___GEN_2011 = VL_RAND_RESET_Q(42);
    vlSelf->top__DOT__axi__DOT__Mem_modle_Rdata = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__axi__DOT__axi_wready = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__axi__DOT__axi_bvalid = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__axi__DOT__axi_rvalid = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__axi__DOT__arlen = VL_RAND_RESET_I(8);
    vlSelf->top__DOT__axi__DOT__awlen = VL_RAND_RESET_I(8);
    vlSelf->top__DOT__axi__DOT__araddr = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__axi__DOT__awaddr = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__axi__DOT__state = VL_RAND_RESET_I(3);
    vlSelf->top__DOT__axi__DOT___GEN_4 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__axi__DOT___GEN_7 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__axi__DOT___GEN_14 = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__axi__DOT___GEN_15 = VL_RAND_RESET_I(8);
    vlSelf->top__DOT__axi__DOT___GEN_18 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__axi__DOT___GEN_27 = VL_RAND_RESET_I(3);
    vlSelf->top__DOT__axi__DOT___GEN_29 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__axi__DOT___GEN_30 = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__axi__DOT___GEN_31 = VL_RAND_RESET_I(8);
    vlSelf->top__DOT__axi__DOT___GEN_35 = VL_RAND_RESET_I(3);
    vlSelf->top__DOT__axi__DOT___GEN_36 = VL_RAND_RESET_I(1);
    vlSelf->__Vtask_pmem_read__1__Rdata = 0;
    for (int __Vi0=0; __Vi0<2; ++__Vi0) {
        vlSelf->__Vm_traceActivity[__Vi0] = VL_RAND_RESET_I(1);
    }
}
