// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design implementation internals
// See Vtop.h for the primary calling header

#include "Vtop___024root.h"
#include "Vtop__Syms.h"

#include "verilated_dpi.h"

void Vtop___024root___eval_initial(Vtop___024root* vlSelf) {
    if (false && vlSelf) {}  // Prevent unused
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root___eval_initial\n"); );
    // Body
    vlSelf->__Vclklast__TOP__clock = vlSelf->clock;
}

void Vtop___024root___settle__TOP__4(Vtop___024root* vlSelf) VL_ATTR_COLD;
void Vtop___024root___settle__TOP__5(Vtop___024root* vlSelf) VL_ATTR_COLD;

void Vtop___024root___eval_settle(Vtop___024root* vlSelf) {
    if (false && vlSelf) {}  // Prevent unused
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root___eval_settle\n"); );
    // Body
    Vtop___024root___settle__TOP__4(vlSelf);
    vlSelf->__Vm_traceActivity[1U] = 1U;
    vlSelf->__Vm_traceActivity[0U] = 1U;
    Vtop___024root___settle__TOP__5(vlSelf);
}

void Vtop___024root___final(Vtop___024root* vlSelf) {
    if (false && vlSelf) {}  // Prevent unused
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root___final\n"); );
}

void Vtop___024root___ctor_var_reset(Vtop___024root* vlSelf) {
    if (false && vlSelf) {}  // Prevent unused
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root___ctor_var_reset\n"); );
    // Body
    vlSelf->clock = VL_RAND_RESET_I(1);
    vlSelf->reset = VL_RAND_RESET_I(1);
    vlSelf->io_inst = VL_RAND_RESET_I(32);
    vlSelf->io_pc = VL_RAND_RESET_Q(64);
    vlSelf->io_step = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__IFU_io_axi_out_rready = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__IDU_io_ds_to_es_valid = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__IDU_io_br_taken = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__IDU_io_br_target = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__IDU_io_ds_allowin = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__IDU_io_ds_ready_go = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__IDU_io_raddr2 = VL_RAND_RESET_I(5);
    vlSelf->top__DOT__EXU_io_es_to_ms_valid = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__EXU_io_es_ld = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__LSU_io_ms_to_ws_valid = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__LSU_io_ms_rf_we = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__LSU_io_ms_fwd_res = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__LSU_io_axi_out_arvalid = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__LSU_io_axi_out_awvalid = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__arbiter_io_ifu_axi_out_rdata = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__arbiter_io_ifu_axi_out_rlast = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__arbiter_io_ifu_axi_out_rvalid = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__arbiter_io_lsu_axi_out_rdata = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__arbiter_io_lsu_axi_out_rlast = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__arbiter_io_lsu_axi_out_rvalid = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__arbiter_io_lsu_axi_out_wready = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__arbiter_io_lsu_axi_out_bvalid = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__arbiter_io_axi_out_arvalid = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__arbiter_io_axi_out_rready = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__arbiter_io_axi_out_awvalid = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__arbiter_io_axi_out_wvalid = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__arbiter_io_axi_out_bready = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache_io_to_ifu_rvalid = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache_io_to_axi_arvalid = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache_io_to_axi_rready = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache_io_to_lsu_rvalid = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache_io_to_lsu_wready = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache_io_to_axi_arlen = VL_RAND_RESET_I(8);
    vlSelf->top__DOT__d_cache_io_to_axi_arvalid = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache_io_to_axi_rready = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache_io_to_axi_awaddr = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__d_cache_io_to_axi_awlen = VL_RAND_RESET_I(8);
    vlSelf->top__DOT__d_cache_io_to_axi_awvalid = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache_io_to_axi_wdata = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__d_cache_io_to_axi_wstrb = VL_RAND_RESET_I(8);
    vlSelf->top__DOT__d_cache_io_to_axi_wvalid = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache_io_to_axi_bready = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__axi_io_axi_out_rlast = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__diff_step = VL_RAND_RESET_I(1);
    for (int __Vi0=0; __Vi0<32; ++__Vi0) {
        vlSelf->top__DOT__Register__DOT__Reg[__Vi0] = VL_RAND_RESET_Q(64);
    }
    for (int __Vi0=0; __Vi0<32; ++__Vi0) {
        vlSelf->top__DOT__Register__DOT__reg_trace__DOT__traceregs[__Vi0] = VL_RAND_RESET_Q(64);
    }
    vlSelf->top__DOT__IFU__DOT__br_target = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__IFU__DOT__fs_valid = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__IFU__DOT__fs_pc_next = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__IFU__DOT__cache_init = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__IFU__DOT___GEN_2 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__IFU__DOT__fs_pc = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__IFU__DOT__fs_inst = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__IFU__DOT__fs_allowin = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__IDU__DOT__ds_valid = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__IDU__DOT__ds_pc = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__IDU__DOT__inst = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__IDU__DOT__br_taken_cancel = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__IDU__DOT__src1_is_pc = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__IDU__DOT___inst_type_T_170 = VL_RAND_RESET_I(7);
    vlSelf->top__DOT__IDU__DOT___inst_type_T_188 = VL_RAND_RESET_I(7);
    vlSelf->top__DOT__IDU__DOT__csr_write = VL_RAND_RESET_I(2);
    vlSelf->top__DOT__IDU__DOT__conflict_es_rs1 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__IDU__DOT__src2_is_imm = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__IDU__DOT__rs2 = VL_RAND_RESET_I(5);
    vlSelf->top__DOT__IDU__DOT__conflict_es_rs2 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__IDU__DOT__conflict_ms_rs1 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__IDU__DOT__conflict_ms_rs2 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__IDU__DOT__conflict_ws_rs1 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__IDU__DOT__conflict_ws_rs2 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__IDU__DOT__ds_ready_go = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__IDU__DOT__ds_allowin = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__IDU__DOT__rdata1 = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__IDU__DOT___rdata2_T_1 = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__IDU__DOT__rdata2 = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__IDU__DOT__br_taken = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__IDU__DOT___GEN_1 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__IDU__DOT___T_7 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__IDU__DOT__imm = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__IDU__DOT___ALUop_T_162 = VL_RAND_RESET_I(7);
    vlSelf->top__DOT__IDU__DOT___ALUop_T_176 = VL_RAND_RESET_I(7);
    vlSelf->top__DOT__IDU__DOT__csr_index = VL_RAND_RESET_I(2);
    vlSelf->top__DOT__IDU__DOT__src1 = VL_RAND_RESET_Q(64);
    for (int __Vi0=0; __Vi0<4; ++__Vi0) {
        vlSelf->top__DOT__IDU__DOT__csr_reg__DOT__CSR_Reg[__Vi0] = VL_RAND_RESET_Q(64);
    }
    vlSelf->top__DOT__IDU__DOT__csr_reg__DOT__CSR_Reg_io_rdata_MPORT_data = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__EXU__DOT__ALU_io_src1_value = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__EXU__DOT__ALU_io_alu_busy = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__EXU__DOT__es_pc = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__EXU__DOT__es_valid = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__EXU__DOT__es_rd = VL_RAND_RESET_I(5);
    vlSelf->top__DOT__EXU__DOT__es_rf_we = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__EXU__DOT__src1_value = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__EXU__DOT__src2_value = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__EXU__DOT__store_data = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__EXU__DOT__st_wstrb = VL_RAND_RESET_I(8);
    vlSelf->top__DOT__EXU__DOT__st_we = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__EXU__DOT__ld_we = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__EXU__DOT__ALUop = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__EXU__DOT__load_type = VL_RAND_RESET_I(3);
    vlSelf->top__DOT__EXU__DOT__es_allowin = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__EXU__DOT__ALU__DOT__Mul_io_mul_valid = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__EXU__DOT__ALU__DOT__Mul_io_result_lo = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__EXU__DOT__ALU__DOT__Div_io_div_valid = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__EXU__DOT__ALU__DOT__Div_io_divw = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__EXU__DOT__ALU__DOT__Div_io_div_signed = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__EXU__DOT__ALU__DOT__Div_io_quotient = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__EXU__DOT__ALU__DOT__Div_io_remainder = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__EXU__DOT__ALU__DOT__mul_valid = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__EXU__DOT__ALU__DOT__div_valid = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__EXU__DOT__ALU__DOT__add_res = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__EXU__DOT__ALU__DOT__sub_res = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__EXU__DOT__ALU__DOT__sra_res = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__EXU__DOT__ALU__DOT__srlw_res = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__EXU__DOT__ALU__DOT__sllw_res = VL_RAND_RESET_Q(63);
    vlSelf->top__DOT__EXU__DOT__ALU__DOT___alu_res_T_80 = VL_RAND_RESET_Q(64);
    VL_RAND_RESET_W(127, vlSelf->top__DOT__EXU__DOT__ALU__DOT__alu_res);
    vlSelf->top__DOT__EXU__DOT__ALU__DOT__Mul__DOT__res = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__EXU__DOT__ALU__DOT__Mul__DOT__state = VL_RAND_RESET_I(2);
    VL_RAND_RESET_W(128, vlSelf->top__DOT__EXU__DOT__ALU__DOT__Mul__DOT__src1);
    VL_RAND_RESET_W(65, vlSelf->top__DOT__EXU__DOT__ALU__DOT__Mul__DOT__src2);
    vlSelf->top__DOT__EXU__DOT__ALU__DOT__Mul__DOT__src1_32 = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__EXU__DOT__ALU__DOT__Mul__DOT___GEN_20 = VL_RAND_RESET_Q(64);
    VL_RAND_RESET_W(130, vlSelf->top__DOT__EXU__DOT__ALU__DOT__Mul__DOT___GEN_30);
    vlSelf->top__DOT__EXU__DOT__ALU__DOT__Div__DOT__dend_neg = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__EXU__DOT__ALU__DOT__Div__DOT__sor_neg = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__EXU__DOT__ALU__DOT__Div__DOT__src1_32_s = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__EXU__DOT__ALU__DOT__Div__DOT__src2_32_s = VL_RAND_RESET_Q(64);
    VL_RAND_RESET_W(128, vlSelf->top__DOT__EXU__DOT__ALU__DOT__Div__DOT__div_cand);
    vlSelf->top__DOT__EXU__DOT__ALU__DOT__Div__DOT__div_start = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__EXU__DOT__ALU__DOT__Div__DOT__quotient = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__EXU__DOT__ALU__DOT__Div__DOT__step_num = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__EXU__DOT__ALU__DOT__Div__DOT___GEN_0 = VL_RAND_RESET_I(1);
    VL_RAND_RESET_W(128, vlSelf->top__DOT__EXU__DOT__ALU__DOT__Div__DOT___GEN_1);
    vlSelf->top__DOT__EXU__DOT__ALU__DOT__Div__DOT___GEN_2 = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__EXU__DOT__ALU__DOT__Div__DOT___GEN_3 = VL_RAND_RESET_I(32);
    VL_RAND_RESET_W(65, vlSelf->top__DOT__EXU__DOT__ALU__DOT__Div__DOT__sub_res);
    vlSelf->top__DOT__EXU__DOT__ALU__DOT__Div__DOT___step_num_T_1 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__EXU__DOT__ALU__DOT__Div__DOT___GEN_14 = VL_RAND_RESET_I(1);
    VL_RAND_RESET_W(129, vlSelf->top__DOT__EXU__DOT__ALU__DOT__Div__DOT___GEN_22);
    VL_RAND_RESET_W(65, vlSelf->top__DOT__EXU__DOT__ALU__DOT__Div__DOT___GEN_23);
    vlSelf->top__DOT__LSU__DOT__ms_valid = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__LSU__DOT__ms_pc = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__LSU__DOT__ms_ready_go = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__LSU__DOT__ms_rf_we = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__LSU__DOT__ms_rf_dst = VL_RAND_RESET_I(5);
    vlSelf->top__DOT__LSU__DOT__ms_res = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__LSU__DOT__store_data = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__LSU__DOT__wen = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__LSU__DOT__wstrb = VL_RAND_RESET_I(8);
    vlSelf->top__DOT__LSU__DOT__ren = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__LSU__DOT__maddr = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__LSU__DOT__load_type = VL_RAND_RESET_I(3);
    vlSelf->top__DOT__LSU__DOT__ms_allowin = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__LSU__DOT___GEN_8 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__LSU__DOT__mem_rdata = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__LSU__DOT___GEN_16 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__LSU__DOT__rdata = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__WBU__DOT__ws_valid = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__WBU__DOT__ws_pc = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__WBU__DOT__ws_rf_we = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__WBU__DOT__ws_rf_dst = VL_RAND_RESET_I(5);
    vlSelf->top__DOT__WBU__DOT__ws_res = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__arbiter__DOT__state = VL_RAND_RESET_I(2);
    vlSelf->top__DOT__arbiter__DOT___GEN_0 = VL_RAND_RESET_I(2);
    vlSelf->top__DOT__arbiter__DOT___GEN_94 = VL_RAND_RESET_I(2);
    vlSelf->top__DOT__arbiter__DOT___GEN_126 = VL_RAND_RESET_I(2);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT__ram_0_0);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT__ram_0_1);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT__ram_0_2);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT__ram_0_3);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT__ram_0_4);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT__ram_0_5);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT__ram_0_6);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT__ram_0_7);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT__ram_0_8);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT__ram_0_9);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT__ram_0_10);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT__ram_0_11);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT__ram_0_12);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT__ram_0_13);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT__ram_0_14);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT__ram_0_15);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT__ram_1_0);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT__ram_1_1);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT__ram_1_2);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT__ram_1_3);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT__ram_1_4);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT__ram_1_5);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT__ram_1_6);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT__ram_1_7);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT__ram_1_8);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT__ram_1_9);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT__ram_1_10);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT__ram_1_11);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT__ram_1_12);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT__ram_1_13);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT__ram_1_14);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT__ram_1_15);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT__ram_2_0);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT__ram_2_1);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT__ram_2_2);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT__ram_2_3);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT__ram_2_4);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT__ram_2_5);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT__ram_2_6);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT__ram_2_7);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT__ram_2_8);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT__ram_2_9);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT__ram_2_10);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT__ram_2_11);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT__ram_2_12);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT__ram_2_13);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT__ram_2_14);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT__ram_2_15);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT__ram_3_0);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT__ram_3_1);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT__ram_3_2);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT__ram_3_3);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT__ram_3_4);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT__ram_3_5);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT__ram_3_6);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT__ram_3_7);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT__ram_3_8);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT__ram_3_9);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT__ram_3_10);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT__ram_3_11);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT__ram_3_12);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT__ram_3_13);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT__ram_3_14);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT__ram_3_15);
    vlSelf->top__DOT__i_cache__DOT__tag_0_0 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT__tag_0_1 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT__tag_0_2 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT__tag_0_3 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT__tag_0_4 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT__tag_0_5 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT__tag_0_6 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT__tag_0_7 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT__tag_0_8 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT__tag_0_9 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT__tag_0_10 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT__tag_0_11 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT__tag_0_12 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT__tag_0_13 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT__tag_0_14 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT__tag_0_15 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT__tag_1_0 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT__tag_1_1 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT__tag_1_2 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT__tag_1_3 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT__tag_1_4 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT__tag_1_5 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT__tag_1_6 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT__tag_1_7 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT__tag_1_8 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT__tag_1_9 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT__tag_1_10 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT__tag_1_11 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT__tag_1_12 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT__tag_1_13 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT__tag_1_14 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT__tag_1_15 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT__tag_2_0 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT__tag_2_1 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT__tag_2_2 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT__tag_2_3 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT__tag_2_4 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT__tag_2_5 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT__tag_2_6 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT__tag_2_7 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT__tag_2_8 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT__tag_2_9 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT__tag_2_10 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT__tag_2_11 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT__tag_2_12 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT__tag_2_13 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT__tag_2_14 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT__tag_2_15 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT__tag_3_0 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT__tag_3_1 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT__tag_3_2 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT__tag_3_3 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT__tag_3_4 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT__tag_3_5 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT__tag_3_6 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT__tag_3_7 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT__tag_3_8 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT__tag_3_9 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT__tag_3_10 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT__tag_3_11 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT__tag_3_12 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT__tag_3_13 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT__tag_3_14 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT__tag_3_15 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT__valid_0_0 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT__valid_0_1 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT__valid_0_2 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT__valid_0_3 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT__valid_0_4 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT__valid_0_5 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT__valid_0_6 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT__valid_0_7 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT__valid_0_8 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT__valid_0_9 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT__valid_0_10 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT__valid_0_11 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT__valid_0_12 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT__valid_0_13 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT__valid_0_14 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT__valid_0_15 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT__valid_1_0 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT__valid_1_1 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT__valid_1_2 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT__valid_1_3 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT__valid_1_4 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT__valid_1_5 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT__valid_1_6 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT__valid_1_7 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT__valid_1_8 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT__valid_1_9 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT__valid_1_10 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT__valid_1_11 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT__valid_1_12 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT__valid_1_13 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT__valid_1_14 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT__valid_1_15 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT__valid_2_0 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT__valid_2_1 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT__valid_2_2 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT__valid_2_3 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT__valid_2_4 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT__valid_2_5 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT__valid_2_6 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT__valid_2_7 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT__valid_2_8 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT__valid_2_9 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT__valid_2_10 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT__valid_2_11 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT__valid_2_12 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT__valid_2_13 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT__valid_2_14 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT__valid_2_15 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT__valid_3_0 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT__valid_3_1 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT__valid_3_2 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT__valid_3_3 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT__valid_3_4 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT__valid_3_5 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT__valid_3_6 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT__valid_3_7 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT__valid_3_8 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT__valid_3_9 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT__valid_3_10 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT__valid_3_11 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT__valid_3_12 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT__valid_3_13 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT__valid_3_14 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT__valid_3_15 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT__addr = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT__receive_data_0 = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__i_cache__DOT__receive_data_1 = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__i_cache__DOT__receive_data_2 = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__i_cache__DOT__receive_data_3 = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__i_cache__DOT__receive_data_4 = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__i_cache__DOT__receive_data_5 = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__i_cache__DOT__receive_data_6 = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__i_cache__DOT__receive_data_7 = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__i_cache__DOT__receive_num = VL_RAND_RESET_I(3);
    vlSelf->top__DOT__i_cache__DOT__quene_0 = VL_RAND_RESET_I(8);
    vlSelf->top__DOT__i_cache__DOT__quene_1 = VL_RAND_RESET_I(8);
    vlSelf->top__DOT__i_cache__DOT__quene_2 = VL_RAND_RESET_I(8);
    vlSelf->top__DOT__i_cache__DOT__quene_3 = VL_RAND_RESET_I(8);
    vlSelf->top__DOT__i_cache__DOT__quene_4 = VL_RAND_RESET_I(8);
    vlSelf->top__DOT__i_cache__DOT__quene_5 = VL_RAND_RESET_I(8);
    vlSelf->top__DOT__i_cache__DOT__quene_6 = VL_RAND_RESET_I(8);
    vlSelf->top__DOT__i_cache__DOT__quene_7 = VL_RAND_RESET_I(8);
    vlSelf->top__DOT__i_cache__DOT__quene_8 = VL_RAND_RESET_I(8);
    vlSelf->top__DOT__i_cache__DOT__quene_9 = VL_RAND_RESET_I(8);
    vlSelf->top__DOT__i_cache__DOT__quene_10 = VL_RAND_RESET_I(8);
    vlSelf->top__DOT__i_cache__DOT__quene_11 = VL_RAND_RESET_I(8);
    vlSelf->top__DOT__i_cache__DOT__quene_12 = VL_RAND_RESET_I(8);
    vlSelf->top__DOT__i_cache__DOT__quene_13 = VL_RAND_RESET_I(8);
    vlSelf->top__DOT__i_cache__DOT__quene_14 = VL_RAND_RESET_I(8);
    vlSelf->top__DOT__i_cache__DOT__quene_15 = VL_RAND_RESET_I(8);
    vlSelf->top__DOT__i_cache__DOT__way0_hit = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT__way1_hit = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT__way2_hit = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT__way3_hit = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT__unuse_way = VL_RAND_RESET_I(3);
    vlSelf->top__DOT__i_cache__DOT__state = VL_RAND_RESET_I(3);
    vlSelf->top__DOT__i_cache__DOT___GEN_132 = VL_RAND_RESET_I(3);
    vlSelf->top__DOT__i_cache__DOT___GEN_144 = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__i_cache__DOT___GEN_145 = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__i_cache__DOT___GEN_146 = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__i_cache__DOT___GEN_147 = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__i_cache__DOT___GEN_148 = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__i_cache__DOT___GEN_149 = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__i_cache__DOT___GEN_150 = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__i_cache__DOT___GEN_151 = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__i_cache__DOT___GEN_152 = VL_RAND_RESET_I(3);
    vlSelf->top__DOT__i_cache__DOT___GEN_153 = VL_RAND_RESET_I(3);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_154);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_155);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_156);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_157);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_158);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_159);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_160);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_161);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_162);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_163);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_164);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_165);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_166);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_167);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_168);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_169);
    vlSelf->top__DOT__i_cache__DOT___GEN_170 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_171 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_172 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_173 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_174 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_175 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_176 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_177 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_178 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_179 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_180 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_181 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_182 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_183 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_184 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_185 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_186 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_187 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_188 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_189 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_190 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_191 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_192 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_193 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_194 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_195 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_196 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_197 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_198 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_199 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_200 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_201 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_217 = VL_RAND_RESET_I(8);
    vlSelf->top__DOT__i_cache__DOT___GEN_218 = VL_RAND_RESET_I(8);
    vlSelf->top__DOT__i_cache__DOT___GEN_219 = VL_RAND_RESET_I(8);
    vlSelf->top__DOT__i_cache__DOT___GEN_220 = VL_RAND_RESET_I(8);
    vlSelf->top__DOT__i_cache__DOT___GEN_221 = VL_RAND_RESET_I(8);
    vlSelf->top__DOT__i_cache__DOT___GEN_222 = VL_RAND_RESET_I(8);
    vlSelf->top__DOT__i_cache__DOT___GEN_223 = VL_RAND_RESET_I(8);
    vlSelf->top__DOT__i_cache__DOT___GEN_224 = VL_RAND_RESET_I(8);
    vlSelf->top__DOT__i_cache__DOT___GEN_225 = VL_RAND_RESET_I(8);
    vlSelf->top__DOT__i_cache__DOT___GEN_226 = VL_RAND_RESET_I(8);
    vlSelf->top__DOT__i_cache__DOT___GEN_227 = VL_RAND_RESET_I(8);
    vlSelf->top__DOT__i_cache__DOT___GEN_228 = VL_RAND_RESET_I(8);
    vlSelf->top__DOT__i_cache__DOT___GEN_229 = VL_RAND_RESET_I(8);
    vlSelf->top__DOT__i_cache__DOT___GEN_230 = VL_RAND_RESET_I(8);
    vlSelf->top__DOT__i_cache__DOT___GEN_231 = VL_RAND_RESET_I(8);
    vlSelf->top__DOT__i_cache__DOT___GEN_232 = VL_RAND_RESET_I(8);
    vlSelf->top__DOT__i_cache__DOT___GEN_233 = VL_RAND_RESET_I(8);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_234);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_235);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_236);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_237);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_238);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_239);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_240);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_241);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_242);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_243);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_244);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_245);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_246);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_247);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_248);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_249);
    vlSelf->top__DOT__i_cache__DOT___GEN_250 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_251 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_252 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_253 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_254 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_255 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_256 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_257 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_258 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_259 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_260 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_261 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_262 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_263 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_264 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_265 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_266 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_267 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_268 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_269 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_270 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_271 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_272 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_273 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_274 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_275 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_276 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_277 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_278 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_279 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_280 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_281 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_282 = VL_RAND_RESET_I(8);
    vlSelf->top__DOT__i_cache__DOT___GEN_283 = VL_RAND_RESET_I(8);
    vlSelf->top__DOT__i_cache__DOT___GEN_284 = VL_RAND_RESET_I(8);
    vlSelf->top__DOT__i_cache__DOT___GEN_285 = VL_RAND_RESET_I(8);
    vlSelf->top__DOT__i_cache__DOT___GEN_286 = VL_RAND_RESET_I(8);
    vlSelf->top__DOT__i_cache__DOT___GEN_287 = VL_RAND_RESET_I(8);
    vlSelf->top__DOT__i_cache__DOT___GEN_288 = VL_RAND_RESET_I(8);
    vlSelf->top__DOT__i_cache__DOT___GEN_289 = VL_RAND_RESET_I(8);
    vlSelf->top__DOT__i_cache__DOT___GEN_290 = VL_RAND_RESET_I(8);
    vlSelf->top__DOT__i_cache__DOT___GEN_291 = VL_RAND_RESET_I(8);
    vlSelf->top__DOT__i_cache__DOT___GEN_292 = VL_RAND_RESET_I(8);
    vlSelf->top__DOT__i_cache__DOT___GEN_293 = VL_RAND_RESET_I(8);
    vlSelf->top__DOT__i_cache__DOT___GEN_294 = VL_RAND_RESET_I(8);
    vlSelf->top__DOT__i_cache__DOT___GEN_295 = VL_RAND_RESET_I(8);
    vlSelf->top__DOT__i_cache__DOT___GEN_296 = VL_RAND_RESET_I(8);
    vlSelf->top__DOT__i_cache__DOT___GEN_297 = VL_RAND_RESET_I(8);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_298);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_299);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_300);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_301);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_302);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_303);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_304);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_305);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_306);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_307);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_308);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_309);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_310);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_311);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_312);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_313);
    vlSelf->top__DOT__i_cache__DOT___GEN_314 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_315 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_316 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_317 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_318 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_319 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_320 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_321 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_322 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_323 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_324 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_325 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_326 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_327 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_328 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_329 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_330 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_331 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_332 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_333 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_334 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_335 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_336 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_337 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_338 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_339 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_340 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_341 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_342 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_343 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_344 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_345 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_346 = VL_RAND_RESET_I(8);
    vlSelf->top__DOT__i_cache__DOT___GEN_347 = VL_RAND_RESET_I(8);
    vlSelf->top__DOT__i_cache__DOT___GEN_348 = VL_RAND_RESET_I(8);
    vlSelf->top__DOT__i_cache__DOT___GEN_349 = VL_RAND_RESET_I(8);
    vlSelf->top__DOT__i_cache__DOT___GEN_350 = VL_RAND_RESET_I(8);
    vlSelf->top__DOT__i_cache__DOT___GEN_351 = VL_RAND_RESET_I(8);
    vlSelf->top__DOT__i_cache__DOT___GEN_352 = VL_RAND_RESET_I(8);
    vlSelf->top__DOT__i_cache__DOT___GEN_353 = VL_RAND_RESET_I(8);
    vlSelf->top__DOT__i_cache__DOT___GEN_354 = VL_RAND_RESET_I(8);
    vlSelf->top__DOT__i_cache__DOT___GEN_355 = VL_RAND_RESET_I(8);
    vlSelf->top__DOT__i_cache__DOT___GEN_356 = VL_RAND_RESET_I(8);
    vlSelf->top__DOT__i_cache__DOT___GEN_357 = VL_RAND_RESET_I(8);
    vlSelf->top__DOT__i_cache__DOT___GEN_358 = VL_RAND_RESET_I(8);
    vlSelf->top__DOT__i_cache__DOT___GEN_359 = VL_RAND_RESET_I(8);
    vlSelf->top__DOT__i_cache__DOT___GEN_360 = VL_RAND_RESET_I(8);
    vlSelf->top__DOT__i_cache__DOT___GEN_361 = VL_RAND_RESET_I(8);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_362);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_363);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_364);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_365);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_366);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_367);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_368);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_369);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_370);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_371);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_372);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_373);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_374);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_375);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_376);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_377);
    vlSelf->top__DOT__i_cache__DOT___GEN_378 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_379 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_380 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_381 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_382 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_383 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_384 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_385 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_386 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_387 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_388 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_389 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_390 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_391 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_392 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_393 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_394 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_395 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_396 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_397 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_398 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_399 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_400 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_401 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_402 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_403 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_404 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_405 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_406 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_407 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_408 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_409 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_410 = VL_RAND_RESET_I(8);
    vlSelf->top__DOT__i_cache__DOT___GEN_411 = VL_RAND_RESET_I(8);
    vlSelf->top__DOT__i_cache__DOT___GEN_412 = VL_RAND_RESET_I(8);
    vlSelf->top__DOT__i_cache__DOT___GEN_413 = VL_RAND_RESET_I(8);
    vlSelf->top__DOT__i_cache__DOT___GEN_414 = VL_RAND_RESET_I(8);
    vlSelf->top__DOT__i_cache__DOT___GEN_415 = VL_RAND_RESET_I(8);
    vlSelf->top__DOT__i_cache__DOT___GEN_416 = VL_RAND_RESET_I(8);
    vlSelf->top__DOT__i_cache__DOT___GEN_417 = VL_RAND_RESET_I(8);
    vlSelf->top__DOT__i_cache__DOT___GEN_418 = VL_RAND_RESET_I(8);
    vlSelf->top__DOT__i_cache__DOT___GEN_419 = VL_RAND_RESET_I(8);
    vlSelf->top__DOT__i_cache__DOT___GEN_420 = VL_RAND_RESET_I(8);
    vlSelf->top__DOT__i_cache__DOT___GEN_421 = VL_RAND_RESET_I(8);
    vlSelf->top__DOT__i_cache__DOT___GEN_422 = VL_RAND_RESET_I(8);
    vlSelf->top__DOT__i_cache__DOT___GEN_423 = VL_RAND_RESET_I(8);
    vlSelf->top__DOT__i_cache__DOT___GEN_424 = VL_RAND_RESET_I(8);
    vlSelf->top__DOT__i_cache__DOT___GEN_425 = VL_RAND_RESET_I(8);
    vlSelf->top__DOT__i_cache__DOT___GEN_2027 = VL_RAND_RESET_I(3);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_2028);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_2029);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_2030);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_2031);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_2032);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_2033);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_2034);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_2035);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_2036);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_2037);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_2038);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_2039);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_2040);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_2041);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_2042);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_2043);
    vlSelf->top__DOT__i_cache__DOT___GEN_2044 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_2045 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_2046 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_2047 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_2048 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_2049 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_2050 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_2051 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_2052 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_2053 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_2054 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_2055 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_2056 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_2057 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_2058 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_2059 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_2060 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_2061 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_2062 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_2063 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_2064 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_2065 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_2066 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_2067 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_2068 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_2069 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_2070 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_2071 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_2072 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_2073 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_2074 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_2075 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_2076 = VL_RAND_RESET_I(8);
    vlSelf->top__DOT__i_cache__DOT___GEN_2077 = VL_RAND_RESET_I(8);
    vlSelf->top__DOT__i_cache__DOT___GEN_2078 = VL_RAND_RESET_I(8);
    vlSelf->top__DOT__i_cache__DOT___GEN_2079 = VL_RAND_RESET_I(8);
    vlSelf->top__DOT__i_cache__DOT___GEN_2080 = VL_RAND_RESET_I(8);
    vlSelf->top__DOT__i_cache__DOT___GEN_2081 = VL_RAND_RESET_I(8);
    vlSelf->top__DOT__i_cache__DOT___GEN_2082 = VL_RAND_RESET_I(8);
    vlSelf->top__DOT__i_cache__DOT___GEN_2083 = VL_RAND_RESET_I(8);
    vlSelf->top__DOT__i_cache__DOT___GEN_2084 = VL_RAND_RESET_I(8);
    vlSelf->top__DOT__i_cache__DOT___GEN_2085 = VL_RAND_RESET_I(8);
    vlSelf->top__DOT__i_cache__DOT___GEN_2086 = VL_RAND_RESET_I(8);
    vlSelf->top__DOT__i_cache__DOT___GEN_2087 = VL_RAND_RESET_I(8);
    vlSelf->top__DOT__i_cache__DOT___GEN_2088 = VL_RAND_RESET_I(8);
    vlSelf->top__DOT__i_cache__DOT___GEN_2089 = VL_RAND_RESET_I(8);
    vlSelf->top__DOT__i_cache__DOT___GEN_2090 = VL_RAND_RESET_I(8);
    vlSelf->top__DOT__i_cache__DOT___GEN_2091 = VL_RAND_RESET_I(8);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_2092);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_2093);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_2094);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_2095);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_2096);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_2097);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_2098);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_2099);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_2100);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_2101);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_2102);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_2103);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_2104);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_2105);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_2106);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_2107);
    vlSelf->top__DOT__i_cache__DOT___GEN_2108 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_2109 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_2110 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_2111 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_2112 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_2113 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_2114 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_2115 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_2116 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_2117 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_2118 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_2119 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_2120 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_2121 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_2122 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_2123 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_2124 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_2125 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_2126 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_2127 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_2128 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_2129 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_2130 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_2131 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_2132 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_2133 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_2134 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_2135 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_2136 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_2137 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_2138 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_2139 = VL_RAND_RESET_I(1);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_2140);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_2141);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_2142);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_2143);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_2144);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_2145);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_2146);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_2147);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_2148);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_2149);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_2150);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_2151);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_2152);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_2153);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_2154);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_2155);
    vlSelf->top__DOT__i_cache__DOT___GEN_2156 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_2157 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_2158 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_2159 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_2160 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_2161 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_2162 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_2163 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_2164 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_2165 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_2166 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_2167 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_2168 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_2169 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_2170 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_2171 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_2172 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_2173 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_2174 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_2175 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_2176 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_2177 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_2178 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_2179 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_2180 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_2181 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_2182 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_2183 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_2184 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_2185 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_2186 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_2187 = VL_RAND_RESET_I(1);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_2188);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_2189);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_2190);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_2191);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_2192);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_2193);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_2194);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_2195);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_2196);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_2197);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_2198);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_2199);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_2200);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_2201);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_2202);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_2203);
    vlSelf->top__DOT__i_cache__DOT___GEN_2204 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_2205 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_2206 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_2207 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_2208 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_2209 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_2210 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_2211 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_2212 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_2213 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_2214 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_2215 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_2216 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_2217 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_2218 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_2219 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_2220 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_2221 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_2222 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_2223 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_2224 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_2225 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_2226 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_2227 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_2228 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_2229 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_2230 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_2231 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_2232 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_2233 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_2234 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_2235 = VL_RAND_RESET_I(1);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_2904);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_2920);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_2936);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_2952);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___io_to_ifu_rdata_T_6);
    vlSelf->top__DOT__i_cache__DOT___GEN_2963 = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__i_cache__DOT___GEN_2964 = VL_RAND_RESET_I(3);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT__ram_0_0);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT__ram_0_1);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT__ram_0_2);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT__ram_0_3);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT__ram_0_4);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT__ram_0_5);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT__ram_0_6);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT__ram_0_7);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT__ram_0_8);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT__ram_0_9);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT__ram_0_10);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT__ram_0_11);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT__ram_0_12);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT__ram_0_13);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT__ram_0_14);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT__ram_0_15);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT__ram_1_0);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT__ram_1_1);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT__ram_1_2);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT__ram_1_3);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT__ram_1_4);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT__ram_1_5);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT__ram_1_6);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT__ram_1_7);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT__ram_1_8);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT__ram_1_9);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT__ram_1_10);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT__ram_1_11);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT__ram_1_12);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT__ram_1_13);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT__ram_1_14);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT__ram_1_15);
    vlSelf->top__DOT__d_cache__DOT__tag_0_0 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__d_cache__DOT__tag_0_1 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__d_cache__DOT__tag_0_2 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__d_cache__DOT__tag_0_3 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__d_cache__DOT__tag_0_4 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__d_cache__DOT__tag_0_5 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__d_cache__DOT__tag_0_6 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__d_cache__DOT__tag_0_7 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__d_cache__DOT__tag_0_8 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__d_cache__DOT__tag_0_9 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__d_cache__DOT__tag_0_10 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__d_cache__DOT__tag_0_11 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__d_cache__DOT__tag_0_12 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__d_cache__DOT__tag_0_13 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__d_cache__DOT__tag_0_14 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__d_cache__DOT__tag_0_15 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__d_cache__DOT__tag_1_0 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__d_cache__DOT__tag_1_1 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__d_cache__DOT__tag_1_2 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__d_cache__DOT__tag_1_3 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__d_cache__DOT__tag_1_4 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__d_cache__DOT__tag_1_5 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__d_cache__DOT__tag_1_6 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__d_cache__DOT__tag_1_7 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__d_cache__DOT__tag_1_8 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__d_cache__DOT__tag_1_9 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__d_cache__DOT__tag_1_10 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__d_cache__DOT__tag_1_11 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__d_cache__DOT__tag_1_12 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__d_cache__DOT__tag_1_13 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__d_cache__DOT__tag_1_14 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__d_cache__DOT__tag_1_15 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__d_cache__DOT__valid_0_0 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT__valid_0_1 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT__valid_0_2 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT__valid_0_3 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT__valid_0_4 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT__valid_0_5 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT__valid_0_6 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT__valid_0_7 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT__valid_0_8 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT__valid_0_9 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT__valid_0_10 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT__valid_0_11 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT__valid_0_12 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT__valid_0_13 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT__valid_0_14 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT__valid_0_15 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT__valid_1_0 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT__valid_1_1 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT__valid_1_2 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT__valid_1_3 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT__valid_1_4 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT__valid_1_5 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT__valid_1_6 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT__valid_1_7 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT__valid_1_8 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT__valid_1_9 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT__valid_1_10 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT__valid_1_11 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT__valid_1_12 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT__valid_1_13 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT__valid_1_14 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT__valid_1_15 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT__dirty_0_0 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT__dirty_0_1 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT__dirty_0_2 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT__dirty_0_3 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT__dirty_0_4 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT__dirty_0_5 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT__dirty_0_6 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT__dirty_0_7 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT__dirty_0_8 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT__dirty_0_9 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT__dirty_0_10 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT__dirty_0_11 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT__dirty_0_12 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT__dirty_0_13 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT__dirty_0_14 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT__dirty_0_15 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT__dirty_1_0 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT__dirty_1_1 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT__dirty_1_2 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT__dirty_1_3 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT__dirty_1_4 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT__dirty_1_5 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT__dirty_1_6 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT__dirty_1_7 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT__dirty_1_8 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT__dirty_1_9 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT__dirty_1_10 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT__dirty_1_11 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT__dirty_1_12 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT__dirty_1_13 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT__dirty_1_14 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT__dirty_1_15 = VL_RAND_RESET_I(1);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT__write_back_data);
    vlSelf->top__DOT__d_cache__DOT__write_back_addr = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__d_cache__DOT__receive_data_0 = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__d_cache__DOT__receive_data_1 = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__d_cache__DOT__receive_data_2 = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__d_cache__DOT__receive_data_3 = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__d_cache__DOT__receive_data_4 = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__d_cache__DOT__receive_data_5 = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__d_cache__DOT__receive_data_6 = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__d_cache__DOT__receive_data_7 = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__d_cache__DOT__receive_num = VL_RAND_RESET_I(3);
    vlSelf->top__DOT__d_cache__DOT__quene_0 = VL_RAND_RESET_I(2);
    vlSelf->top__DOT__d_cache__DOT__quene_1 = VL_RAND_RESET_I(2);
    vlSelf->top__DOT__d_cache__DOT__quene_2 = VL_RAND_RESET_I(2);
    vlSelf->top__DOT__d_cache__DOT__quene_3 = VL_RAND_RESET_I(2);
    vlSelf->top__DOT__d_cache__DOT__quene_4 = VL_RAND_RESET_I(2);
    vlSelf->top__DOT__d_cache__DOT__quene_5 = VL_RAND_RESET_I(2);
    vlSelf->top__DOT__d_cache__DOT__quene_6 = VL_RAND_RESET_I(2);
    vlSelf->top__DOT__d_cache__DOT__quene_7 = VL_RAND_RESET_I(2);
    vlSelf->top__DOT__d_cache__DOT__quene_8 = VL_RAND_RESET_I(2);
    vlSelf->top__DOT__d_cache__DOT__quene_9 = VL_RAND_RESET_I(2);
    vlSelf->top__DOT__d_cache__DOT__quene_10 = VL_RAND_RESET_I(2);
    vlSelf->top__DOT__d_cache__DOT__quene_11 = VL_RAND_RESET_I(2);
    vlSelf->top__DOT__d_cache__DOT__quene_12 = VL_RAND_RESET_I(2);
    vlSelf->top__DOT__d_cache__DOT__quene_13 = VL_RAND_RESET_I(2);
    vlSelf->top__DOT__d_cache__DOT__quene_14 = VL_RAND_RESET_I(2);
    vlSelf->top__DOT__d_cache__DOT__quene_15 = VL_RAND_RESET_I(2);
    vlSelf->top__DOT__d_cache__DOT__wmask = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__d_cache__DOT___GEN_15 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__d_cache__DOT__way0_hit = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_47 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__d_cache__DOT__way1_hit = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT__unuse_way = VL_RAND_RESET_I(2);
    vlSelf->top__DOT__d_cache__DOT__state = VL_RAND_RESET_I(4);
    vlSelf->top__DOT__d_cache__DOT___GEN_70 = VL_RAND_RESET_I(3);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___GEN_88);
    VL_RAND_RESET_W(575, vlSelf->top__DOT__d_cache__DOT___ram_0_T_5);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___GEN_136);
    VL_RAND_RESET_W(575, vlSelf->top__DOT__d_cache__DOT___ram_1_T_5);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___GEN_203);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___GEN_204);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___GEN_205);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___GEN_206);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___GEN_207);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___GEN_208);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___GEN_209);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___GEN_210);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___GEN_211);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___GEN_212);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___GEN_213);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___GEN_214);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___GEN_215);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___GEN_216);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___GEN_217);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___GEN_218);
    vlSelf->top__DOT__d_cache__DOT___GEN_219 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_220 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_221 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_222 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_223 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_224 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_225 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_226 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_227 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_228 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_229 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_230 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_231 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_232 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_233 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_234 = VL_RAND_RESET_I(1);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___GEN_235);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___GEN_236);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___GEN_237);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___GEN_238);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___GEN_239);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___GEN_240);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___GEN_241);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___GEN_242);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___GEN_243);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___GEN_244);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___GEN_245);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___GEN_246);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___GEN_247);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___GEN_248);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___GEN_249);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___GEN_250);
    vlSelf->top__DOT__d_cache__DOT___GEN_251 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_252 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_253 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_254 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_255 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_256 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_257 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_258 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_259 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_260 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_261 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_262 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_263 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_264 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_265 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_266 = VL_RAND_RESET_I(1);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___GEN_287);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___GEN_288);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___GEN_289);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___GEN_290);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___GEN_291);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___GEN_292);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___GEN_293);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___GEN_294);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___GEN_295);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___GEN_296);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___GEN_297);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___GEN_298);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___GEN_299);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___GEN_300);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___GEN_301);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___GEN_302);
    vlSelf->top__DOT__d_cache__DOT___GEN_303 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__d_cache__DOT___GEN_304 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__d_cache__DOT___GEN_305 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__d_cache__DOT___GEN_306 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__d_cache__DOT___GEN_307 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__d_cache__DOT___GEN_308 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__d_cache__DOT___GEN_309 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__d_cache__DOT___GEN_310 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__d_cache__DOT___GEN_311 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__d_cache__DOT___GEN_312 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__d_cache__DOT___GEN_313 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__d_cache__DOT___GEN_314 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__d_cache__DOT___GEN_315 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__d_cache__DOT___GEN_316 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__d_cache__DOT___GEN_317 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__d_cache__DOT___GEN_318 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__d_cache__DOT___GEN_319 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_320 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_321 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_322 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_323 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_324 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_325 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_326 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_327 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_328 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_329 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_330 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_331 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_332 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_333 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_334 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_351 = VL_RAND_RESET_I(2);
    vlSelf->top__DOT__d_cache__DOT___GEN_352 = VL_RAND_RESET_I(2);
    vlSelf->top__DOT__d_cache__DOT___GEN_353 = VL_RAND_RESET_I(2);
    vlSelf->top__DOT__d_cache__DOT___GEN_354 = VL_RAND_RESET_I(2);
    vlSelf->top__DOT__d_cache__DOT___GEN_355 = VL_RAND_RESET_I(2);
    vlSelf->top__DOT__d_cache__DOT___GEN_356 = VL_RAND_RESET_I(2);
    vlSelf->top__DOT__d_cache__DOT___GEN_357 = VL_RAND_RESET_I(2);
    vlSelf->top__DOT__d_cache__DOT___GEN_358 = VL_RAND_RESET_I(2);
    vlSelf->top__DOT__d_cache__DOT___GEN_359 = VL_RAND_RESET_I(2);
    vlSelf->top__DOT__d_cache__DOT___GEN_360 = VL_RAND_RESET_I(2);
    vlSelf->top__DOT__d_cache__DOT___GEN_361 = VL_RAND_RESET_I(2);
    vlSelf->top__DOT__d_cache__DOT___GEN_362 = VL_RAND_RESET_I(2);
    vlSelf->top__DOT__d_cache__DOT___GEN_363 = VL_RAND_RESET_I(2);
    vlSelf->top__DOT__d_cache__DOT___GEN_364 = VL_RAND_RESET_I(2);
    vlSelf->top__DOT__d_cache__DOT___GEN_365 = VL_RAND_RESET_I(2);
    vlSelf->top__DOT__d_cache__DOT___GEN_366 = VL_RAND_RESET_I(2);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___GEN_367);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___GEN_368);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___GEN_369);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___GEN_370);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___GEN_371);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___GEN_372);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___GEN_373);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___GEN_374);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___GEN_375);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___GEN_376);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___GEN_377);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___GEN_378);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___GEN_379);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___GEN_380);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___GEN_381);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___GEN_382);
    vlSelf->top__DOT__d_cache__DOT___GEN_383 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__d_cache__DOT___GEN_384 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__d_cache__DOT___GEN_385 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__d_cache__DOT___GEN_386 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__d_cache__DOT___GEN_387 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__d_cache__DOT___GEN_388 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__d_cache__DOT___GEN_389 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__d_cache__DOT___GEN_390 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__d_cache__DOT___GEN_391 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__d_cache__DOT___GEN_392 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__d_cache__DOT___GEN_393 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__d_cache__DOT___GEN_394 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__d_cache__DOT___GEN_395 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__d_cache__DOT___GEN_396 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__d_cache__DOT___GEN_397 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__d_cache__DOT___GEN_398 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__d_cache__DOT___GEN_399 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_400 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_401 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_402 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_403 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_404 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_405 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_406 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_407 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_408 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_409 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_410 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_411 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_412 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_413 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_414 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_415 = VL_RAND_RESET_I(2);
    vlSelf->top__DOT__d_cache__DOT___GEN_416 = VL_RAND_RESET_I(2);
    vlSelf->top__DOT__d_cache__DOT___GEN_417 = VL_RAND_RESET_I(2);
    vlSelf->top__DOT__d_cache__DOT___GEN_418 = VL_RAND_RESET_I(2);
    vlSelf->top__DOT__d_cache__DOT___GEN_419 = VL_RAND_RESET_I(2);
    vlSelf->top__DOT__d_cache__DOT___GEN_420 = VL_RAND_RESET_I(2);
    vlSelf->top__DOT__d_cache__DOT___GEN_421 = VL_RAND_RESET_I(2);
    vlSelf->top__DOT__d_cache__DOT___GEN_422 = VL_RAND_RESET_I(2);
    vlSelf->top__DOT__d_cache__DOT___GEN_423 = VL_RAND_RESET_I(2);
    vlSelf->top__DOT__d_cache__DOT___GEN_424 = VL_RAND_RESET_I(2);
    vlSelf->top__DOT__d_cache__DOT___GEN_425 = VL_RAND_RESET_I(2);
    vlSelf->top__DOT__d_cache__DOT___GEN_426 = VL_RAND_RESET_I(2);
    vlSelf->top__DOT__d_cache__DOT___GEN_427 = VL_RAND_RESET_I(2);
    vlSelf->top__DOT__d_cache__DOT___GEN_428 = VL_RAND_RESET_I(2);
    vlSelf->top__DOT__d_cache__DOT___GEN_429 = VL_RAND_RESET_I(2);
    vlSelf->top__DOT__d_cache__DOT___GEN_430 = VL_RAND_RESET_I(2);
    vlSelf->top__DOT__d_cache__DOT___GEN_446 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_689 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_1659 = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__d_cache__DOT___GEN_1660 = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__d_cache__DOT___GEN_1661 = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__d_cache__DOT___GEN_1662 = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__d_cache__DOT___GEN_1663 = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__d_cache__DOT___GEN_1664 = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__d_cache__DOT___GEN_1665 = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__d_cache__DOT___GEN_1666 = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__d_cache__DOT___GEN_1667 = VL_RAND_RESET_I(3);
    vlSelf->top__DOT__d_cache__DOT___GEN_1668 = VL_RAND_RESET_I(4);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___GEN_1669);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___GEN_1670);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___GEN_1671);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___GEN_1672);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___GEN_1673);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___GEN_1674);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___GEN_1675);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___GEN_1676);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___GEN_1677);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___GEN_1678);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___GEN_1679);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___GEN_1680);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___GEN_1681);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___GEN_1682);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___GEN_1683);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___GEN_1684);
    vlSelf->top__DOT__d_cache__DOT___GEN_1685 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__d_cache__DOT___GEN_1686 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__d_cache__DOT___GEN_1687 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__d_cache__DOT___GEN_1688 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__d_cache__DOT___GEN_1689 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__d_cache__DOT___GEN_1690 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__d_cache__DOT___GEN_1691 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__d_cache__DOT___GEN_1692 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__d_cache__DOT___GEN_1693 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__d_cache__DOT___GEN_1694 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__d_cache__DOT___GEN_1695 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__d_cache__DOT___GEN_1696 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__d_cache__DOT___GEN_1697 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__d_cache__DOT___GEN_1698 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__d_cache__DOT___GEN_1699 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__d_cache__DOT___GEN_1700 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__d_cache__DOT___GEN_1701 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_1702 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_1703 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_1704 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_1705 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_1706 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_1707 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_1708 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_1709 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_1710 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_1711 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_1712 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_1713 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_1714 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_1715 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_1716 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_1717 = VL_RAND_RESET_I(2);
    vlSelf->top__DOT__d_cache__DOT___GEN_1718 = VL_RAND_RESET_I(2);
    vlSelf->top__DOT__d_cache__DOT___GEN_1719 = VL_RAND_RESET_I(2);
    vlSelf->top__DOT__d_cache__DOT___GEN_1720 = VL_RAND_RESET_I(2);
    vlSelf->top__DOT__d_cache__DOT___GEN_1721 = VL_RAND_RESET_I(2);
    vlSelf->top__DOT__d_cache__DOT___GEN_1722 = VL_RAND_RESET_I(2);
    vlSelf->top__DOT__d_cache__DOT___GEN_1723 = VL_RAND_RESET_I(2);
    vlSelf->top__DOT__d_cache__DOT___GEN_1724 = VL_RAND_RESET_I(2);
    vlSelf->top__DOT__d_cache__DOT___GEN_1725 = VL_RAND_RESET_I(2);
    vlSelf->top__DOT__d_cache__DOT___GEN_1726 = VL_RAND_RESET_I(2);
    vlSelf->top__DOT__d_cache__DOT___GEN_1727 = VL_RAND_RESET_I(2);
    vlSelf->top__DOT__d_cache__DOT___GEN_1728 = VL_RAND_RESET_I(2);
    vlSelf->top__DOT__d_cache__DOT___GEN_1729 = VL_RAND_RESET_I(2);
    vlSelf->top__DOT__d_cache__DOT___GEN_1730 = VL_RAND_RESET_I(2);
    vlSelf->top__DOT__d_cache__DOT___GEN_1731 = VL_RAND_RESET_I(2);
    vlSelf->top__DOT__d_cache__DOT___GEN_1732 = VL_RAND_RESET_I(2);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___GEN_1733);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___GEN_1734);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___GEN_1735);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___GEN_1736);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___GEN_1737);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___GEN_1738);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___GEN_1739);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___GEN_1740);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___GEN_1741);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___GEN_1742);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___GEN_1743);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___GEN_1744);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___GEN_1745);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___GEN_1746);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___GEN_1747);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___GEN_1748);
    vlSelf->top__DOT__d_cache__DOT___GEN_1749 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__d_cache__DOT___GEN_1750 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__d_cache__DOT___GEN_1751 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__d_cache__DOT___GEN_1752 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__d_cache__DOT___GEN_1753 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__d_cache__DOT___GEN_1754 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__d_cache__DOT___GEN_1755 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__d_cache__DOT___GEN_1756 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__d_cache__DOT___GEN_1757 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__d_cache__DOT___GEN_1758 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__d_cache__DOT___GEN_1759 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__d_cache__DOT___GEN_1760 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__d_cache__DOT___GEN_1761 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__d_cache__DOT___GEN_1762 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__d_cache__DOT___GEN_1763 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__d_cache__DOT___GEN_1764 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__d_cache__DOT___GEN_1765 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_1766 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_1767 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_1768 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_1769 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_1770 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_1771 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_1772 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_1773 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_1774 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_1775 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_1776 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_1777 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_1778 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_1779 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_1780 = VL_RAND_RESET_I(1);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___GEN_1781);
    vlSelf->top__DOT__d_cache__DOT___GEN_1783 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_1784 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_1785 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_1786 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_1787 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_1788 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_1789 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_1790 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_1791 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_1792 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_1793 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_1794 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_1795 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_1796 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_1797 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_1798 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_1799 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_1800 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_1801 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_1802 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_1803 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_1804 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_1805 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_1806 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_1807 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_1808 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_1809 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_1810 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_1811 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_1812 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_1813 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_1814 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_2289 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_2409 = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__d_cache__DOT___GEN_2507 = VL_RAND_RESET_Q(42);
    vlSelf->top__DOT__axi__DOT__Mem_modle_Rdata = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__axi__DOT__axi_wready = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__axi__DOT__axi_bvalid = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__axi__DOT__axi_rvalid = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__axi__DOT__arlen = VL_RAND_RESET_I(8);
    vlSelf->top__DOT__axi__DOT__awlen = VL_RAND_RESET_I(8);
    vlSelf->top__DOT__axi__DOT__araddr = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__axi__DOT__awaddr = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__axi__DOT__state = VL_RAND_RESET_I(3);
    vlSelf->top__DOT__axi__DOT___GEN_4 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__axi__DOT___GEN_7 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__axi__DOT___GEN_14 = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__axi__DOT___GEN_15 = VL_RAND_RESET_I(8);
    vlSelf->top__DOT__axi__DOT___GEN_18 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__axi__DOT___GEN_27 = VL_RAND_RESET_I(3);
    vlSelf->top__DOT__axi__DOT___GEN_29 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__axi__DOT___GEN_30 = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__axi__DOT___GEN_31 = VL_RAND_RESET_I(8);
    vlSelf->top__DOT__axi__DOT___GEN_35 = VL_RAND_RESET_I(3);
    vlSelf->top__DOT__axi__DOT___GEN_36 = VL_RAND_RESET_I(1);
    vlSelf->__Vtask_pmem_read__1__Rdata = 0;
    vlSelf->__Vdlyvset__top__DOT__Register__DOT__Reg__v0 = 0;
    vlSelf->__Vdly__top__DOT__IFU__DOT__fs_pc_next = VL_RAND_RESET_Q(64);
    vlSelf->__Vdlyvset__top__DOT__IDU__DOT__csr_reg__DOT__CSR_Reg__v0 = 0;
    vlSelf->__Vdlyvset__top__DOT__IDU__DOT__csr_reg__DOT__CSR_Reg__v1 = 0;
    vlSelf->__Vdly__top__DOT__EXU__DOT__ALU__DOT__Mul__DOT__state = VL_RAND_RESET_I(2);
    VL_RAND_RESET_W(65, vlSelf->__Vdly__top__DOT__EXU__DOT__ALU__DOT__Mul__DOT__src2);
    vlSelf->__Vdly__top__DOT__EXU__DOT__ALU__DOT__Div__DOT__div_start = VL_RAND_RESET_I(1);
    vlSelf->__Vdly__top__DOT__LSU__DOT__wen = VL_RAND_RESET_I(1);
    vlSelf->__Vdly__top__DOT__LSU__DOT__ren = VL_RAND_RESET_I(1);
    vlSelf->__Vdly__top__DOT__arbiter__DOT__state = VL_RAND_RESET_I(2);
    vlSelf->__Vdly__top__DOT__i_cache__DOT__state = VL_RAND_RESET_I(3);
    vlSelf->__Vdly__top__DOT__d_cache__DOT__state = VL_RAND_RESET_I(4);
    vlSelf->__Vdly__top__DOT__axi__DOT__awlen = VL_RAND_RESET_I(8);
    vlSelf->__Vdly__top__DOT__axi__DOT__state = VL_RAND_RESET_I(3);
    for (int __Vi0=0; __Vi0<2; ++__Vi0) {
        vlSelf->__Vm_traceActivity[__Vi0] = VL_RAND_RESET_I(1);
    }
}
