// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design implementation internals
// See Vtop.h for the primary calling header

#include "Vtop___024root.h"
#include "Vtop__Syms.h"

#include "verilated_dpi.h"

void Vtop___024root___eval_initial(Vtop___024root* vlSelf) {
    if (false && vlSelf) {}  // Prevent unused
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root___eval_initial\n"); );
    // Body
    vlSelf->__Vclklast__TOP__clock = vlSelf->clock;
}

void Vtop___024root___settle__TOP__3(Vtop___024root* vlSelf) VL_ATTR_COLD;

void Vtop___024root___eval_settle(Vtop___024root* vlSelf) {
    if (false && vlSelf) {}  // Prevent unused
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root___eval_settle\n"); );
    // Body
    Vtop___024root___settle__TOP__3(vlSelf);
    vlSelf->__Vm_traceActivity[1U] = 1U;
    vlSelf->__Vm_traceActivity[0U] = 1U;
}

void Vtop___024root___final(Vtop___024root* vlSelf) {
    if (false && vlSelf) {}  // Prevent unused
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root___final\n"); );
}

void Vtop___024root___ctor_var_reset(Vtop___024root* vlSelf) {
    if (false && vlSelf) {}  // Prevent unused
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root___ctor_var_reset\n"); );
    // Body
    vlSelf->clock = VL_RAND_RESET_I(1);
    vlSelf->reset = VL_RAND_RESET_I(1);
    vlSelf->io_inst = VL_RAND_RESET_I(32);
    vlSelf->io_pc = VL_RAND_RESET_Q(64);
    vlSelf->io_step = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__Register_io_rdata1 = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__Register_io_rdata2 = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__IFU_io_fs_to_ds_valid = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__IDU_io_ds_to_es_valid = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__IDU_io_ds_allowin = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__IDU_io_raddr2 = VL_RAND_RESET_I(5);
    vlSelf->top__DOT__EXU_io_es_allowin = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__EXU_io_es_to_ms_valid = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__LSU_io_ms_allowin = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__LSU_io_ms_to_ws_valid = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__LSU_io_ms_rf_we = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__LSU_io_axi_out_arvalid = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__LSU_io_axi_out_awvalid = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__arbiter_io_ifu_axi_out_rdata = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__arbiter_io_ifu_axi_out_rlast = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__arbiter_io_ifu_axi_out_rvalid = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__arbiter_io_lsu_axi_out_rdata = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__arbiter_io_lsu_axi_out_rlast = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__arbiter_io_lsu_axi_out_rvalid = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__arbiter_io_lsu_axi_out_wready = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__arbiter_io_lsu_axi_out_bvalid = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__arbiter_io_axi_out_arvalid = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__arbiter_io_axi_out_rready = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__arbiter_io_axi_out_awvalid = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__arbiter_io_axi_out_wvalid = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__arbiter_io_axi_out_bready = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache_io_to_ifu_rvalid = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache_io_to_axi_arvalid = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache_io_to_axi_rready = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache_io_to_lsu_rvalid = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache_io_to_lsu_wready = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache_io_to_axi_arlen = VL_RAND_RESET_I(8);
    vlSelf->top__DOT__d_cache_io_to_axi_arvalid = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache_io_to_axi_rready = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache_io_to_axi_awaddr = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__d_cache_io_to_axi_awlen = VL_RAND_RESET_I(8);
    vlSelf->top__DOT__d_cache_io_to_axi_awvalid = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache_io_to_axi_wdata = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__d_cache_io_to_axi_wstrb = VL_RAND_RESET_I(8);
    vlSelf->top__DOT__d_cache_io_to_axi_wvalid = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache_io_to_axi_bready = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__axi_io_axi_out_rlast = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__diff_step = VL_RAND_RESET_I(1);
    for (int __Vi0=0; __Vi0<32; ++__Vi0) {
        vlSelf->top__DOT__Register__DOT__Reg[__Vi0] = VL_RAND_RESET_Q(64);
    }
    for (int __Vi0=0; __Vi0<32; ++__Vi0) {
        vlSelf->top__DOT__Register__DOT__reg_trace__DOT__traceregs[__Vi0] = VL_RAND_RESET_Q(64);
    }
    vlSelf->top__DOT__IFU__DOT__fs_valid = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__IFU__DOT__fs_ready_go = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__IFU__DOT__cache_init = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__IFU__DOT__fs_to_ds_valid = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__IFU__DOT___GEN_1 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__IFU__DOT__fs_pc = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__IFU__DOT__fs_inst = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__IFU__DOT___GEN_3 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__IFU__DOT__seq_pc = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__IFU__DOT__fs_allowin = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__IFU__DOT___GEN_5 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__IFU__DOT__inst_ready = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__IFU__DOT___GEN_7 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__IDU__DOT__ds_valid = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__IDU__DOT__ds_pc = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__IDU__DOT__inst = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__IDU__DOT__br_taken_cancel = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__IDU__DOT__src1_is_pc = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__IDU__DOT___inst_type_T_188 = VL_RAND_RESET_I(7);
    vlSelf->top__DOT__IDU__DOT__csr_write = VL_RAND_RESET_I(2);
    vlSelf->top__DOT__IDU__DOT__src2_is_imm = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__IDU__DOT__rs2 = VL_RAND_RESET_I(5);
    vlSelf->top__DOT__IDU__DOT__conflict = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__IDU__DOT___ALUop_T_176 = VL_RAND_RESET_I(7);
    vlSelf->top__DOT__IDU__DOT__ds_ready_go = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__IDU__DOT__ds_allowin = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__IDU__DOT__br_taken = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__IDU__DOT___T_2 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__IDU__DOT__imm = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__IDU__DOT__csr_index = VL_RAND_RESET_I(2);
    vlSelf->top__DOT__IDU__DOT__src1 = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__IDU__DOT___br_target_T_1 = VL_RAND_RESET_Q(64);
    for (int __Vi0=0; __Vi0<4; ++__Vi0) {
        vlSelf->top__DOT__IDU__DOT__csr_reg__DOT__CSR_Reg[__Vi0] = VL_RAND_RESET_Q(64);
    }
    vlSelf->top__DOT__IDU__DOT__csr_reg__DOT__CSR_Reg_io_rdata_MPORT_data = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__EXU__DOT__ALU_io_src1_value = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__EXU__DOT__ALU_io_alu_busy = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__EXU__DOT__es_pc = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__EXU__DOT__es_valid = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__EXU__DOT__es_rd = VL_RAND_RESET_I(5);
    vlSelf->top__DOT__EXU__DOT__es_rf_we = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__EXU__DOT__src1_value = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__EXU__DOT__src2_value = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__EXU__DOT__store_data = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__EXU__DOT__st_wstrb = VL_RAND_RESET_I(8);
    vlSelf->top__DOT__EXU__DOT__st_we = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__EXU__DOT__ld_we = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__EXU__DOT__ALUop = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__EXU__DOT__load_type = VL_RAND_RESET_I(3);
    vlSelf->top__DOT__EXU__DOT__ALU__DOT__Mul_io_mul_valid = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__EXU__DOT__ALU__DOT__Mul_io_result_lo = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__EXU__DOT__ALU__DOT__Div_io_div_valid = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__EXU__DOT__ALU__DOT__Div_io_divw = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__EXU__DOT__ALU__DOT__Div_io_div_signed = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__EXU__DOT__ALU__DOT__Div_io_quotient = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__EXU__DOT__ALU__DOT__Div_io_remainder = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__EXU__DOT__ALU__DOT__mul_valid = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__EXU__DOT__ALU__DOT__div_valid = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__EXU__DOT__ALU__DOT__add_res = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__EXU__DOT__ALU__DOT__sub_res = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__EXU__DOT__ALU__DOT__sra_res = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__EXU__DOT__ALU__DOT__srlw_res = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__EXU__DOT__ALU__DOT__sllw_res = VL_RAND_RESET_Q(63);
    vlSelf->top__DOT__EXU__DOT__ALU__DOT___alu_res_T_50 = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__EXU__DOT__ALU__DOT___alu_res_T_98 = VL_RAND_RESET_Q(64);
    VL_RAND_RESET_W(127, vlSelf->top__DOT__EXU__DOT__ALU__DOT__alu_res);
    vlSelf->top__DOT__EXU__DOT__ALU__DOT__Mul__DOT__res = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__EXU__DOT__ALU__DOT__Mul__DOT__state = VL_RAND_RESET_I(2);
    VL_RAND_RESET_W(128, vlSelf->top__DOT__EXU__DOT__ALU__DOT__Mul__DOT__src1);
    VL_RAND_RESET_W(65, vlSelf->top__DOT__EXU__DOT__ALU__DOT__Mul__DOT__src2);
    vlSelf->top__DOT__EXU__DOT__ALU__DOT__Mul__DOT__src1_32 = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__EXU__DOT__ALU__DOT__Mul__DOT___GEN_20 = VL_RAND_RESET_Q(64);
    VL_RAND_RESET_W(130, vlSelf->top__DOT__EXU__DOT__ALU__DOT__Mul__DOT___GEN_30);
    vlSelf->top__DOT__EXU__DOT__ALU__DOT__Div__DOT__dend_neg = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__EXU__DOT__ALU__DOT__Div__DOT__sor_neg = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__EXU__DOT__ALU__DOT__Div__DOT__src1_32_s = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__EXU__DOT__ALU__DOT__Div__DOT__src2_32_s = VL_RAND_RESET_Q(64);
    VL_RAND_RESET_W(128, vlSelf->top__DOT__EXU__DOT__ALU__DOT__Div__DOT__div_cand);
    vlSelf->top__DOT__EXU__DOT__ALU__DOT__Div__DOT__div_start = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__EXU__DOT__ALU__DOT__Div__DOT__quotient = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__EXU__DOT__ALU__DOT__Div__DOT__step_num = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__EXU__DOT__ALU__DOT__Div__DOT___GEN_0 = VL_RAND_RESET_I(1);
    VL_RAND_RESET_W(128, vlSelf->top__DOT__EXU__DOT__ALU__DOT__Div__DOT___GEN_1);
    vlSelf->top__DOT__EXU__DOT__ALU__DOT__Div__DOT___GEN_2 = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__EXU__DOT__ALU__DOT__Div__DOT___GEN_3 = VL_RAND_RESET_I(32);
    VL_RAND_RESET_W(65, vlSelf->top__DOT__EXU__DOT__ALU__DOT__Div__DOT__sub_res);
    vlSelf->top__DOT__EXU__DOT__ALU__DOT__Div__DOT___step_num_T_1 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__EXU__DOT__ALU__DOT__Div__DOT___GEN_14 = VL_RAND_RESET_I(1);
    VL_RAND_RESET_W(129, vlSelf->top__DOT__EXU__DOT__ALU__DOT__Div__DOT___GEN_22);
    VL_RAND_RESET_W(65, vlSelf->top__DOT__EXU__DOT__ALU__DOT__Div__DOT___GEN_23);
    vlSelf->top__DOT__LSU__DOT__ms_valid = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__LSU__DOT__ms_pc = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__LSU__DOT__ms_ready_go = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__LSU__DOT__ms_rf_we = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__LSU__DOT__ms_rf_dst = VL_RAND_RESET_I(5);
    vlSelf->top__DOT__LSU__DOT__ms_res = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__LSU__DOT__store_data = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__LSU__DOT__wen = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__LSU__DOT__wstrb = VL_RAND_RESET_I(8);
    vlSelf->top__DOT__LSU__DOT__ren = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__LSU__DOT__maddr = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__LSU__DOT__load_type = VL_RAND_RESET_I(3);
    vlSelf->top__DOT__LSU__DOT___GEN_8 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__LSU__DOT__mem_rdata = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__LSU__DOT___GEN_16 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__WBU__DOT__ws_valid = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__WBU__DOT__ws_pc = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__WBU__DOT__ws_rf_we = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__WBU__DOT__ws_rf_dst = VL_RAND_RESET_I(5);
    vlSelf->top__DOT__WBU__DOT__ws_res = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__arbiter__DOT__state = VL_RAND_RESET_I(2);
    vlSelf->top__DOT__arbiter__DOT___GEN_0 = VL_RAND_RESET_I(2);
    vlSelf->top__DOT__arbiter__DOT___GEN_94 = VL_RAND_RESET_I(2);
    vlSelf->top__DOT__arbiter__DOT___GEN_126 = VL_RAND_RESET_I(2);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT__ram_0_0);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT__ram_0_1);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT__ram_0_2);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT__ram_0_3);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT__ram_0_4);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT__ram_0_5);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT__ram_0_6);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT__ram_0_7);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT__ram_0_8);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT__ram_0_9);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT__ram_0_10);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT__ram_0_11);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT__ram_0_12);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT__ram_0_13);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT__ram_0_14);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT__ram_0_15);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT__ram_1_0);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT__ram_1_1);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT__ram_1_2);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT__ram_1_3);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT__ram_1_4);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT__ram_1_5);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT__ram_1_6);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT__ram_1_7);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT__ram_1_8);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT__ram_1_9);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT__ram_1_10);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT__ram_1_11);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT__ram_1_12);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT__ram_1_13);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT__ram_1_14);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT__ram_1_15);
    vlSelf->top__DOT__i_cache__DOT__tag_0_0 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT__tag_0_1 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT__tag_0_2 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT__tag_0_3 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT__tag_0_4 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT__tag_0_5 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT__tag_0_6 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT__tag_0_7 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT__tag_0_8 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT__tag_0_9 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT__tag_0_10 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT__tag_0_11 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT__tag_0_12 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT__tag_0_13 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT__tag_0_14 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT__tag_0_15 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT__tag_1_0 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT__tag_1_1 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT__tag_1_2 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT__tag_1_3 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT__tag_1_4 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT__tag_1_5 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT__tag_1_6 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT__tag_1_7 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT__tag_1_8 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT__tag_1_9 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT__tag_1_10 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT__tag_1_11 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT__tag_1_12 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT__tag_1_13 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT__tag_1_14 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT__tag_1_15 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT__valid_0_0 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT__valid_0_1 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT__valid_0_2 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT__valid_0_3 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT__valid_0_4 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT__valid_0_5 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT__valid_0_6 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT__valid_0_7 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT__valid_0_8 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT__valid_0_9 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT__valid_0_10 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT__valid_0_11 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT__valid_0_12 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT__valid_0_13 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT__valid_0_14 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT__valid_0_15 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT__valid_1_0 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT__valid_1_1 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT__valid_1_2 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT__valid_1_3 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT__valid_1_4 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT__valid_1_5 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT__valid_1_6 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT__valid_1_7 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT__valid_1_8 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT__valid_1_9 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT__valid_1_10 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT__valid_1_11 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT__valid_1_12 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT__valid_1_13 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT__valid_1_14 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT__valid_1_15 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT__way0_hit = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT__way1_hit = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT__unuse_way = VL_RAND_RESET_I(2);
    vlSelf->top__DOT__i_cache__DOT__receive_data_0 = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__i_cache__DOT__receive_data_1 = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__i_cache__DOT__receive_data_2 = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__i_cache__DOT__receive_data_3 = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__i_cache__DOT__receive_data_4 = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__i_cache__DOT__receive_data_5 = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__i_cache__DOT__receive_data_6 = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__i_cache__DOT__receive_data_7 = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__i_cache__DOT__receive_num = VL_RAND_RESET_I(3);
    vlSelf->top__DOT__i_cache__DOT__quene = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_13 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_31 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_46 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_64 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT__state = VL_RAND_RESET_I(3);
    vlSelf->top__DOT__i_cache__DOT___GEN_70 = VL_RAND_RESET_I(3);
    vlSelf->top__DOT__i_cache__DOT___GEN_72 = VL_RAND_RESET_I(3);
    vlSelf->top__DOT__i_cache__DOT___GEN_84 = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__i_cache__DOT___GEN_85 = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__i_cache__DOT___GEN_86 = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__i_cache__DOT___GEN_87 = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__i_cache__DOT___GEN_88 = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__i_cache__DOT___GEN_89 = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__i_cache__DOT___GEN_90 = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__i_cache__DOT___GEN_91 = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__i_cache__DOT___GEN_92 = VL_RAND_RESET_I(3);
    vlSelf->top__DOT__i_cache__DOT___GEN_93 = VL_RAND_RESET_I(3);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___ram_0_T);
    vlSelf->top__DOT__i_cache__DOT___GEN_110 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_111 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_112 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_113 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_114 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_115 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_116 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_117 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_118 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_119 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_120 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_121 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_122 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_123 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_124 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_125 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_643 = VL_RAND_RESET_I(3);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_644);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_645);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_646);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_647);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_648);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_649);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_650);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_651);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_652);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_653);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_654);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_655);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_656);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_657);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_658);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_659);
    vlSelf->top__DOT__i_cache__DOT___GEN_660 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_661 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_662 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_663 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_664 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_665 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_666 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_667 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_668 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_669 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_670 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_671 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_672 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_673 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_674 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_675 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_676 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_677 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_678 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_679 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_680 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_681 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_682 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_683 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_684 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_685 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_686 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_687 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_688 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_689 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_690 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_691 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_692 = VL_RAND_RESET_I(1);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_693);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_694);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_695);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_696);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_697);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_698);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_699);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_700);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_701);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_702);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_703);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_704);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_705);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_706);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_707);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_708);
    vlSelf->top__DOT__i_cache__DOT___GEN_709 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_710 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_711 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_712 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_713 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_714 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_715 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_716 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_717 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_718 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_719 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_720 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_721 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_722 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_723 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_724 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__i_cache__DOT___GEN_725 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_726 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_727 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_728 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_729 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_730 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_731 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_732 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_733 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_734 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_735 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_736 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_737 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_738 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_739 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_740 = VL_RAND_RESET_I(1);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_1075);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__i_cache__DOT___GEN_1091);
    vlSelf->top__DOT__i_cache__DOT___GEN_1100 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__i_cache__DOT___GEN_1109 = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__i_cache__DOT___GEN_1110 = VL_RAND_RESET_I(3);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT__ram_0_0);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT__ram_0_1);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT__ram_0_2);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT__ram_0_3);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT__ram_0_4);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT__ram_0_5);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT__ram_0_6);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT__ram_0_7);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT__ram_0_8);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT__ram_0_9);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT__ram_0_10);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT__ram_0_11);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT__ram_0_12);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT__ram_0_13);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT__ram_0_14);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT__ram_0_15);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT__ram_1_0);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT__ram_1_1);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT__ram_1_2);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT__ram_1_3);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT__ram_1_4);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT__ram_1_5);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT__ram_1_6);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT__ram_1_7);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT__ram_1_8);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT__ram_1_9);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT__ram_1_10);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT__ram_1_11);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT__ram_1_12);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT__ram_1_13);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT__ram_1_14);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT__ram_1_15);
    vlSelf->top__DOT__d_cache__DOT__tag_0_0 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__d_cache__DOT__tag_0_1 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__d_cache__DOT__tag_0_2 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__d_cache__DOT__tag_0_3 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__d_cache__DOT__tag_0_4 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__d_cache__DOT__tag_0_5 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__d_cache__DOT__tag_0_6 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__d_cache__DOT__tag_0_7 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__d_cache__DOT__tag_0_8 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__d_cache__DOT__tag_0_9 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__d_cache__DOT__tag_0_10 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__d_cache__DOT__tag_0_11 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__d_cache__DOT__tag_0_12 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__d_cache__DOT__tag_0_13 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__d_cache__DOT__tag_0_14 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__d_cache__DOT__tag_0_15 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__d_cache__DOT__tag_1_0 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__d_cache__DOT__tag_1_1 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__d_cache__DOT__tag_1_2 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__d_cache__DOT__tag_1_3 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__d_cache__DOT__tag_1_4 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__d_cache__DOT__tag_1_5 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__d_cache__DOT__tag_1_6 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__d_cache__DOT__tag_1_7 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__d_cache__DOT__tag_1_8 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__d_cache__DOT__tag_1_9 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__d_cache__DOT__tag_1_10 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__d_cache__DOT__tag_1_11 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__d_cache__DOT__tag_1_12 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__d_cache__DOT__tag_1_13 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__d_cache__DOT__tag_1_14 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__d_cache__DOT__tag_1_15 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__d_cache__DOT__valid_0_0 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT__valid_0_1 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT__valid_0_2 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT__valid_0_3 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT__valid_0_4 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT__valid_0_5 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT__valid_0_6 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT__valid_0_7 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT__valid_0_8 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT__valid_0_9 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT__valid_0_10 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT__valid_0_11 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT__valid_0_12 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT__valid_0_13 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT__valid_0_14 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT__valid_0_15 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT__valid_1_0 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT__valid_1_1 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT__valid_1_2 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT__valid_1_3 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT__valid_1_4 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT__valid_1_5 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT__valid_1_6 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT__valid_1_7 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT__valid_1_8 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT__valid_1_9 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT__valid_1_10 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT__valid_1_11 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT__valid_1_12 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT__valid_1_13 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT__valid_1_14 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT__valid_1_15 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT__dirty_0_0 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT__dirty_0_1 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT__dirty_0_2 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT__dirty_0_3 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT__dirty_0_4 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT__dirty_0_5 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT__dirty_0_6 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT__dirty_0_7 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT__dirty_0_8 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT__dirty_0_9 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT__dirty_0_10 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT__dirty_0_11 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT__dirty_0_12 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT__dirty_0_13 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT__dirty_0_14 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT__dirty_0_15 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT__dirty_1_0 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT__dirty_1_1 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT__dirty_1_2 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT__dirty_1_3 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT__dirty_1_4 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT__dirty_1_5 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT__dirty_1_6 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT__dirty_1_7 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT__dirty_1_8 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT__dirty_1_9 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT__dirty_1_10 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT__dirty_1_11 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT__dirty_1_12 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT__dirty_1_13 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT__dirty_1_14 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT__dirty_1_15 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT__way0_hit = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT__way1_hit = VL_RAND_RESET_I(1);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT__write_back_data);
    vlSelf->top__DOT__d_cache__DOT__write_back_addr = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__d_cache__DOT__unuse_way = VL_RAND_RESET_I(2);
    vlSelf->top__DOT__d_cache__DOT__receive_data_0 = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__d_cache__DOT__receive_data_1 = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__d_cache__DOT__receive_data_2 = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__d_cache__DOT__receive_data_3 = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__d_cache__DOT__receive_data_4 = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__d_cache__DOT__receive_data_5 = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__d_cache__DOT__receive_data_6 = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__d_cache__DOT__receive_data_7 = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__d_cache__DOT__receive_num = VL_RAND_RESET_I(3);
    vlSelf->top__DOT__d_cache__DOT__quene = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT__wmask = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__d_cache__DOT___GEN_15 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__d_cache__DOT___GEN_31 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_48 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__d_cache__DOT___GEN_64 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT__state = VL_RAND_RESET_I(4);
    vlSelf->top__DOT__d_cache__DOT___GEN_74 = VL_RAND_RESET_I(3);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___GEN_92);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___GEN_140);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___GEN_207);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___GEN_208);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___GEN_209);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___GEN_210);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___GEN_211);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___GEN_212);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___GEN_213);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___GEN_214);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___GEN_215);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___GEN_216);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___GEN_217);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___GEN_218);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___GEN_219);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___GEN_220);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___GEN_221);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___GEN_222);
    vlSelf->top__DOT__d_cache__DOT___GEN_223 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_224 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_225 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_226 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_227 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_228 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_229 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_230 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_231 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_232 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_233 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_234 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_235 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_236 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_237 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_238 = VL_RAND_RESET_I(1);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___GEN_239);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___GEN_240);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___GEN_241);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___GEN_242);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___GEN_243);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___GEN_244);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___GEN_245);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___GEN_246);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___GEN_247);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___GEN_248);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___GEN_249);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___GEN_250);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___GEN_251);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___GEN_252);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___GEN_253);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___GEN_254);
    vlSelf->top__DOT__d_cache__DOT___GEN_255 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_256 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_257 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_258 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_259 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_260 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_261 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_262 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_263 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_264 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_265 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_266 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_267 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_268 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_269 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_270 = VL_RAND_RESET_I(1);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___ram_0_T_6);
    vlSelf->top__DOT__d_cache__DOT___GEN_402 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_598 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_1447 = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__d_cache__DOT___GEN_1448 = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__d_cache__DOT___GEN_1449 = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__d_cache__DOT___GEN_1450 = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__d_cache__DOT___GEN_1451 = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__d_cache__DOT___GEN_1452 = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__d_cache__DOT___GEN_1453 = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__d_cache__DOT___GEN_1454 = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__d_cache__DOT___GEN_1455 = VL_RAND_RESET_I(3);
    vlSelf->top__DOT__d_cache__DOT___GEN_1456 = VL_RAND_RESET_I(4);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___GEN_1457);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___GEN_1458);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___GEN_1459);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___GEN_1460);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___GEN_1461);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___GEN_1462);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___GEN_1463);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___GEN_1464);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___GEN_1465);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___GEN_1466);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___GEN_1467);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___GEN_1468);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___GEN_1469);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___GEN_1470);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___GEN_1471);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___GEN_1472);
    vlSelf->top__DOT__d_cache__DOT___GEN_1473 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__d_cache__DOT___GEN_1474 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__d_cache__DOT___GEN_1475 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__d_cache__DOT___GEN_1476 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__d_cache__DOT___GEN_1477 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__d_cache__DOT___GEN_1478 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__d_cache__DOT___GEN_1479 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__d_cache__DOT___GEN_1480 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__d_cache__DOT___GEN_1481 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__d_cache__DOT___GEN_1482 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__d_cache__DOT___GEN_1483 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__d_cache__DOT___GEN_1484 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__d_cache__DOT___GEN_1485 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__d_cache__DOT___GEN_1486 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__d_cache__DOT___GEN_1487 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__d_cache__DOT___GEN_1488 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__d_cache__DOT___GEN_1489 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_1490 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_1491 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_1492 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_1493 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_1494 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_1495 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_1496 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_1497 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_1498 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_1499 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_1500 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_1501 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_1502 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_1503 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_1504 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_1505 = VL_RAND_RESET_I(1);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___GEN_1506);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___GEN_1507);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___GEN_1508);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___GEN_1509);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___GEN_1510);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___GEN_1511);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___GEN_1512);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___GEN_1513);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___GEN_1514);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___GEN_1515);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___GEN_1516);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___GEN_1517);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___GEN_1518);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___GEN_1519);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___GEN_1520);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___GEN_1521);
    vlSelf->top__DOT__d_cache__DOT___GEN_1522 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__d_cache__DOT___GEN_1523 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__d_cache__DOT___GEN_1524 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__d_cache__DOT___GEN_1525 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__d_cache__DOT___GEN_1526 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__d_cache__DOT___GEN_1527 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__d_cache__DOT___GEN_1528 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__d_cache__DOT___GEN_1529 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__d_cache__DOT___GEN_1530 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__d_cache__DOT___GEN_1531 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__d_cache__DOT___GEN_1532 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__d_cache__DOT___GEN_1533 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__d_cache__DOT___GEN_1534 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__d_cache__DOT___GEN_1535 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__d_cache__DOT___GEN_1536 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__d_cache__DOT___GEN_1537 = VL_RAND_RESET_I(32);
    vlSelf->top__DOT__d_cache__DOT___GEN_1538 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_1539 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_1540 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_1541 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_1542 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_1543 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_1544 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_1545 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_1546 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_1547 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_1548 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_1549 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_1550 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_1551 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_1552 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_1553 = VL_RAND_RESET_I(1);
    VL_RAND_RESET_W(512, vlSelf->top__DOT__d_cache__DOT___GEN_1554);
    vlSelf->top__DOT__d_cache__DOT___GEN_1556 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_1557 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_1558 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_1559 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_1560 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_1561 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_1562 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_1563 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_1564 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_1565 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_1566 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_1567 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_1568 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_1569 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_1570 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_1571 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_1572 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_1573 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_1574 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_1575 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_1576 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_1577 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_1578 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_1579 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_1580 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_1581 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_1582 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_1583 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_1584 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_1585 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_1586 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_1587 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_2017 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__d_cache__DOT___GEN_2137 = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__d_cache__DOT___GEN_2235 = VL_RAND_RESET_Q(42);
    vlSelf->top__DOT__axi__DOT__Mem_modle_Rdata = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__axi__DOT__axi_wready = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__axi__DOT__axi_bvalid = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__axi__DOT__axi_rvalid = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__axi__DOT__arlen = VL_RAND_RESET_I(8);
    vlSelf->top__DOT__axi__DOT__awlen = VL_RAND_RESET_I(8);
    vlSelf->top__DOT__axi__DOT__araddr = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__axi__DOT__awaddr = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__axi__DOT__state = VL_RAND_RESET_I(3);
    vlSelf->top__DOT__axi__DOT___GEN_4 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__axi__DOT___GEN_7 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__axi__DOT___GEN_14 = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__axi__DOT___GEN_15 = VL_RAND_RESET_I(8);
    vlSelf->top__DOT__axi__DOT___GEN_18 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__axi__DOT___GEN_27 = VL_RAND_RESET_I(3);
    vlSelf->top__DOT__axi__DOT___GEN_29 = VL_RAND_RESET_I(1);
    vlSelf->top__DOT__axi__DOT___GEN_30 = VL_RAND_RESET_Q(64);
    vlSelf->top__DOT__axi__DOT___GEN_31 = VL_RAND_RESET_I(8);
    vlSelf->top__DOT__axi__DOT___GEN_35 = VL_RAND_RESET_I(3);
    vlSelf->top__DOT__axi__DOT___GEN_36 = VL_RAND_RESET_I(1);
    vlSelf->__Vtask_pmem_read__1__Rdata = 0;
    vlSelf->__Vdly__top__DOT__IFU__DOT__fs_inst = VL_RAND_RESET_I(32);
    for (int __Vi0=0; __Vi0<2; ++__Vi0) {
        vlSelf->__Vm_traceActivity[__Vi0] = VL_RAND_RESET_I(1);
    }
}
